// Predefined map configurations

export interface MapPreset {
  id: string;
  label: string;
  description: string;
  config: object;
}

const pavone: object = {
  simulation: {
    grid_width: 25,
    grid_height: 25,
    timestep_duration_ms: 50,
    max_steps: 5000,
    seed: 42,
  },
  warehouse: {
    position: { x: 1, y: 1 },
    width: 2,
    height: 2,
    warehouse_cells: [
      { x: 11, y: 1 },
      { x: 12, y: 1 },
      { x: 11, y: 2 },
      { x: 12, y: 2 },
      { x: 1, y: 11 },
      { x: 2, y: 11 },
      { x: 22, y: 11 },
      { x: 23, y: 11 },
      { x: 1, y: 12 },
      { x: 2, y: 12 },
      { x: 22, y: 12 },
      { x: 23, y: 12 },
      { x: 11, y: 22 },
      { x: 12, y: 22 },
      { x: 11, y: 23 },
      { x: 12, y: 23 },
    ],
    entrances: [
      { x: 11, y: 3 },
      { x: 3, y: 11 },
      { x: 21, y: 11 },
      { x: 11, y: 21 },
    ],
    exits: [
      { x: 12, y: 3 },
      { x: 3, y: 12 },
      { x: 21, y: 12 },
      { x: 12, y: 21 },
    ],
    recharge_rate: 5,
  },
  obstacles: [
    { type: "wall", start: { x: 10, y: 0 }, end: { x: 10, y: 0 } },
    { type: "wall", start: { x: 11, y: 0 }, end: { x: 11, y: 0 } },
    { type: "wall", start: { x: 12, y: 0 }, end: { x: 12, y: 0 } },
    { type: "wall", start: { x: 13, y: 0 }, end: { x: 13, y: 0 } },
    { type: "wall", start: { x: 10, y: 1 }, end: { x: 10, y: 1 } },
    { type: "wall", start: { x: 13, y: 1 }, end: { x: 13, y: 1 } },
    { type: "wall", start: { x: 10, y: 2 }, end: { x: 10, y: 2 } },
    { type: "wall", start: { x: 13, y: 2 }, end: { x: 13, y: 2 } },
    { type: "wall", start: { x: 10, y: 3 }, end: { x: 10, y: 3 } },
    { type: "wall", start: { x: 13, y: 3 }, end: { x: 13, y: 3 } },
    { type: "wall", start: { x: 5, y: 5 }, end: { x: 5, y: 5 } },
    { type: "wall", start: { x: 6, y: 5 }, end: { x: 6, y: 5 } },
    { type: "wall", start: { x: 9, y: 5 }, end: { x: 9, y: 5 } },
    { type: "wall", start: { x: 10, y: 5 }, end: { x: 10, y: 5 } },
    { type: "wall", start: { x: 13, y: 5 }, end: { x: 13, y: 5 } },
    { type: "wall", start: { x: 14, y: 5 }, end: { x: 14, y: 5 } },
    { type: "wall", start: { x: 17, y: 5 }, end: { x: 17, y: 5 } },
    { type: "wall", start: { x: 18, y: 5 }, end: { x: 18, y: 5 } },
    { type: "wall", start: { x: 5, y: 6 }, end: { x: 5, y: 6 } },
    { type: "wall", start: { x: 6, y: 6 }, end: { x: 6, y: 6 } },
    { type: "wall", start: { x: 9, y: 6 }, end: { x: 9, y: 6 } },
    { type: "wall", start: { x: 10, y: 6 }, end: { x: 10, y: 6 } },
    { type: "wall", start: { x: 13, y: 6 }, end: { x: 13, y: 6 } },
    { type: "wall", start: { x: 14, y: 6 }, end: { x: 14, y: 6 } },
    { type: "wall", start: { x: 17, y: 6 }, end: { x: 17, y: 6 } },
    { type: "wall", start: { x: 18, y: 6 }, end: { x: 18, y: 6 } },
    { type: "wall", start: { x: 5, y: 7 }, end: { x: 5, y: 7 } },
    { type: "wall", start: { x: 6, y: 7 }, end: { x: 6, y: 7 } },
    { type: "wall", start: { x: 9, y: 7 }, end: { x: 9, y: 7 } },
    { type: "wall", start: { x: 10, y: 7 }, end: { x: 10, y: 7 } },
    { type: "wall", start: { x: 13, y: 7 }, end: { x: 13, y: 7 } },
    { type: "wall", start: { x: 14, y: 7 }, end: { x: 14, y: 7 } },
    { type: "wall", start: { x: 17, y: 7 }, end: { x: 17, y: 7 } },
    { type: "wall", start: { x: 18, y: 7 }, end: { x: 18, y: 7 } },
    { type: "wall", start: { x: 0, y: 10 }, end: { x: 0, y: 10 } },
    { type: "wall", start: { x: 1, y: 10 }, end: { x: 1, y: 10 } },
    { type: "wall", start: { x: 2, y: 10 }, end: { x: 2, y: 10 } },
    { type: "wall", start: { x: 3, y: 10 }, end: { x: 3, y: 10 } },
    { type: "wall", start: { x: 21, y: 10 }, end: { x: 21, y: 10 } },
    { type: "wall", start: { x: 22, y: 10 }, end: { x: 22, y: 10 } },
    { type: "wall", start: { x: 23, y: 10 }, end: { x: 23, y: 10 } },
    { type: "wall", start: { x: 24, y: 10 }, end: { x: 24, y: 10 } },
    { type: "wall", start: { x: 0, y: 11 }, end: { x: 0, y: 11 } },
    { type: "wall", start: { x: 24, y: 11 }, end: { x: 24, y: 11 } },
    { type: "wall", start: { x: 0, y: 12 }, end: { x: 0, y: 12 } },
    { type: "wall", start: { x: 24, y: 12 }, end: { x: 24, y: 12 } },
    { type: "wall", start: { x: 0, y: 13 }, end: { x: 0, y: 13 } },
    { type: "wall", start: { x: 1, y: 13 }, end: { x: 1, y: 13 } },
    { type: "wall", start: { x: 2, y: 13 }, end: { x: 2, y: 13 } },
    { type: "wall", start: { x: 3, y: 13 }, end: { x: 3, y: 13 } },
    { type: "wall", start: { x: 21, y: 13 }, end: { x: 21, y: 13 } },
    { type: "wall", start: { x: 22, y: 13 }, end: { x: 22, y: 13 } },
    { type: "wall", start: { x: 23, y: 13 }, end: { x: 23, y: 13 } },
    { type: "wall", start: { x: 24, y: 13 }, end: { x: 24, y: 13 } },
    { type: "wall", start: { x: 5, y: 15 }, end: { x: 5, y: 15 } },
    { type: "wall", start: { x: 6, y: 15 }, end: { x: 6, y: 15 } },
    { type: "wall", start: { x: 9, y: 15 }, end: { x: 9, y: 15 } },
    { type: "wall", start: { x: 10, y: 15 }, end: { x: 10, y: 15 } },
    { type: "wall", start: { x: 13, y: 15 }, end: { x: 13, y: 15 } },
    { type: "wall", start: { x: 14, y: 15 }, end: { x: 14, y: 15 } },
    { type: "wall", start: { x: 17, y: 15 }, end: { x: 17, y: 15 } },
    { type: "wall", start: { x: 18, y: 15 }, end: { x: 18, y: 15 } },
    { type: "wall", start: { x: 5, y: 16 }, end: { x: 5, y: 16 } },
    { type: "wall", start: { x: 6, y: 16 }, end: { x: 6, y: 16 } },
    { type: "wall", start: { x: 9, y: 16 }, end: { x: 9, y: 16 } },
    { type: "wall", start: { x: 10, y: 16 }, end: { x: 10, y: 16 } },
    { type: "wall", start: { x: 13, y: 16 }, end: { x: 13, y: 16 } },
    { type: "wall", start: { x: 14, y: 16 }, end: { x: 14, y: 16 } },
    { type: "wall", start: { x: 17, y: 16 }, end: { x: 17, y: 16 } },
    { type: "wall", start: { x: 18, y: 16 }, end: { x: 18, y: 16 } },
    { type: "wall", start: { x: 5, y: 17 }, end: { x: 5, y: 17 } },
    { type: "wall", start: { x: 6, y: 17 }, end: { x: 6, y: 17 } },
    { type: "wall", start: { x: 9, y: 17 }, end: { x: 9, y: 17 } },
    { type: "wall", start: { x: 10, y: 17 }, end: { x: 10, y: 17 } },
    { type: "wall", start: { x: 13, y: 17 }, end: { x: 13, y: 17 } },
    { type: "wall", start: { x: 14, y: 17 }, end: { x: 14, y: 17 } },
    { type: "wall", start: { x: 17, y: 17 }, end: { x: 17, y: 17 } },
    { type: "wall", start: { x: 18, y: 17 }, end: { x: 18, y: 17 } },
    { type: "wall", start: { x: 10, y: 21 }, end: { x: 10, y: 21 } },
    { type: "wall", start: { x: 13, y: 21 }, end: { x: 13, y: 21 } },
    { type: "wall", start: { x: 10, y: 22 }, end: { x: 10, y: 22 } },
    { type: "wall", start: { x: 13, y: 22 }, end: { x: 13, y: 22 } },
    { type: "wall", start: { x: 10, y: 23 }, end: { x: 10, y: 23 } },
    { type: "wall", start: { x: 13, y: 23 }, end: { x: 13, y: 23 } },
    { type: "wall", start: { x: 10, y: 24 }, end: { x: 10, y: 24 } },
    { type: "wall", start: { x: 11, y: 24 }, end: { x: 11, y: 24 } },
    { type: "wall", start: { x: 12, y: 24 }, end: { x: 12, y: 24 } },
    { type: "wall", start: { x: 13, y: 24 }, end: { x: 13, y: 24 } },
  ],
  objects: {
    count: 20,
    spawn_zones: [{ x_range: [4, 20], y_range: [4, 17], probability: 1 }],
  },
  agents: {
    scouts: {
      count: 2,
      parameters: {
        vision_radius: 5,
        communication_radius: 15,
        max_energy: 100,
        speed: 1.5,
        carrying_capacity: 0,
      },
    },
    coordinators: {
      count: 1,
      parameters: {
        vision_radius: 7,
        communication_radius: 20,
        max_energy: 120,
        speed: 1,
        carrying_capacity: 0,
      },
    },
    retrievers: {
      count: 3,
      parameters: {
        vision_radius: 4,
        communication_radius: 12,
        max_energy: 100,
        speed: 1,
        carrying_capacity: 2,
      },
    },
  },
  logging: {
    enabled: true,
    log_interval: 10,
    metrics: ["coverage", "energy", "objects_retrieved"],
  },
};

const pavoneComplex: object = {
  simulation: {
    grid_width: 25,
    grid_height: 25,
    timestep_duration_ms: 50,
    max_steps: 5000,
    seed: 42,
  },
  warehouse: {
    position: { x: 1, y: 1 },
    width: 2,
    height: 2,
    warehouse_cells: [
      { x: 11, y: 1 },
      { x: 12, y: 1 },
      { x: 11, y: 2 },
      { x: 12, y: 2 },
      { x: 1, y: 11 },
      { x: 2, y: 11 },
      { x: 22, y: 11 },
      { x: 23, y: 11 },
      { x: 1, y: 12 },
      { x: 2, y: 12 },
      { x: 22, y: 12 },
      { x: 23, y: 12 },
      { x: 11, y: 22 },
      { x: 12, y: 22 },
      { x: 11, y: 23 },
      { x: 12, y: 23 },
    ],
    entrances: [
      { x: 11, y: 3 },
      { x: 3, y: 11 },
      { x: 21, y: 11 },
      { x: 11, y: 21 },
    ],
    exits: [
      { x: 12, y: 3 },
      { x: 3, y: 12 },
      { x: 21, y: 12 },
      { x: 12, y: 21 },
    ],
    recharge_rate: 5,
  },
  obstacles: [
    { type: "wall", start: { x: 10, y: 0 }, end: { x: 10, y: 0 } },
    { type: "wall", start: { x: 11, y: 0 }, end: { x: 11, y: 0 } },
    { type: "wall", start: { x: 12, y: 0 }, end: { x: 12, y: 0 } },
    { type: "wall", start: { x: 13, y: 0 }, end: { x: 13, y: 0 } },
    { type: "wall", start: { x: 10, y: 1 }, end: { x: 10, y: 1 } },
    { type: "wall", start: { x: 13, y: 1 }, end: { x: 13, y: 1 } },
    { type: "wall", start: { x: 2, y: 2 }, end: { x: 2, y: 2 } },
    { type: "wall", start: { x: 3, y: 2 }, end: { x: 3, y: 2 } },
    { type: "wall", start: { x: 4, y: 2 }, end: { x: 4, y: 2 } },
    { type: "wall", start: { x: 5, y: 2 }, end: { x: 5, y: 2 } },
    { type: "wall", start: { x: 6, y: 2 }, end: { x: 6, y: 2 } },
    { type: "wall", start: { x: 7, y: 2 }, end: { x: 7, y: 2 } },
    { type: "wall", start: { x: 10, y: 2 }, end: { x: 10, y: 2 } },
    { type: "wall", start: { x: 13, y: 2 }, end: { x: 13, y: 2 } },
    { type: "wall", start: { x: 16, y: 2 }, end: { x: 16, y: 2 } },
    { type: "wall", start: { x: 17, y: 2 }, end: { x: 17, y: 2 } },
    { type: "wall", start: { x: 18, y: 2 }, end: { x: 18, y: 2 } },
    { type: "wall", start: { x: 19, y: 2 }, end: { x: 19, y: 2 } },
    { type: "wall", start: { x: 20, y: 2 }, end: { x: 20, y: 2 } },
    { type: "wall", start: { x: 21, y: 2 }, end: { x: 21, y: 2 } },
    { type: "wall", start: { x: 2, y: 3 }, end: { x: 2, y: 3 } },
    { type: "wall", start: { x: 3, y: 3 }, end: { x: 3, y: 3 } },
    { type: "wall", start: { x: 4, y: 3 }, end: { x: 4, y: 3 } },
    { type: "wall", start: { x: 5, y: 3 }, end: { x: 5, y: 3 } },
    { type: "wall", start: { x: 6, y: 3 }, end: { x: 6, y: 3 } },
    { type: "wall", start: { x: 7, y: 3 }, end: { x: 7, y: 3 } },
    { type: "wall", start: { x: 10, y: 3 }, end: { x: 10, y: 3 } },
    { type: "wall", start: { x: 13, y: 3 }, end: { x: 13, y: 3 } },
    { type: "wall", start: { x: 16, y: 3 }, end: { x: 16, y: 3 } },
    { type: "wall", start: { x: 17, y: 3 }, end: { x: 17, y: 3 } },
    { type: "wall", start: { x: 18, y: 3 }, end: { x: 18, y: 3 } },
    { type: "wall", start: { x: 19, y: 3 }, end: { x: 19, y: 3 } },
    { type: "wall", start: { x: 20, y: 3 }, end: { x: 20, y: 3 } },
    { type: "wall", start: { x: 21, y: 3 }, end: { x: 21, y: 3 } },
    { type: "wall", start: { x: 2, y: 5 }, end: { x: 2, y: 5 } },
    { type: "wall", start: { x: 3, y: 5 }, end: { x: 3, y: 5 } },
    { type: "wall", start: { x: 4, y: 5 }, end: { x: 4, y: 5 } },
    { type: "wall", start: { x: 5, y: 5 }, end: { x: 5, y: 5 } },
    { type: "wall", start: { x: 6, y: 5 }, end: { x: 6, y: 5 } },
    { type: "wall", start: { x: 7, y: 5 }, end: { x: 7, y: 5 } },
    { type: "wall", start: { x: 9, y: 5 }, end: { x: 9, y: 5 } },
    { type: "wall", start: { x: 10, y: 5 }, end: { x: 10, y: 5 } },
    { type: "wall", start: { x: 11, y: 5 }, end: { x: 11, y: 5 } },
    { type: "wall", start: { x: 12, y: 5 }, end: { x: 12, y: 5 } },
    { type: "wall", start: { x: 13, y: 5 }, end: { x: 13, y: 5 } },
    { type: "wall", start: { x: 14, y: 5 }, end: { x: 14, y: 5 } },
    { type: "wall", start: { x: 16, y: 5 }, end: { x: 16, y: 5 } },
    { type: "wall", start: { x: 17, y: 5 }, end: { x: 17, y: 5 } },
    { type: "wall", start: { x: 18, y: 5 }, end: { x: 18, y: 5 } },
    { type: "wall", start: { x: 19, y: 5 }, end: { x: 19, y: 5 } },
    { type: "wall", start: { x: 20, y: 5 }, end: { x: 20, y: 5 } },
    { type: "wall", start: { x: 21, y: 5 }, end: { x: 21, y: 5 } },
    { type: "wall", start: { x: 2, y: 6 }, end: { x: 2, y: 6 } },
    { type: "wall", start: { x: 3, y: 6 }, end: { x: 3, y: 6 } },
    { type: "wall", start: { x: 4, y: 6 }, end: { x: 4, y: 6 } },
    { type: "wall", start: { x: 5, y: 6 }, end: { x: 5, y: 6 } },
    { type: "wall", start: { x: 6, y: 6 }, end: { x: 6, y: 6 } },
    { type: "wall", start: { x: 7, y: 6 }, end: { x: 7, y: 6 } },
    { type: "wall", start: { x: 9, y: 6 }, end: { x: 9, y: 6 } },
    { type: "wall", start: { x: 10, y: 6 }, end: { x: 10, y: 6 } },
    { type: "wall", start: { x: 11, y: 6 }, end: { x: 11, y: 6 } },
    { type: "wall", start: { x: 12, y: 6 }, end: { x: 12, y: 6 } },
    { type: "wall", start: { x: 13, y: 6 }, end: { x: 13, y: 6 } },
    { type: "wall", start: { x: 14, y: 6 }, end: { x: 14, y: 6 } },
    { type: "wall", start: { x: 16, y: 6 }, end: { x: 16, y: 6 } },
    { type: "wall", start: { x: 17, y: 6 }, end: { x: 17, y: 6 } },
    { type: "wall", start: { x: 18, y: 6 }, end: { x: 18, y: 6 } },
    { type: "wall", start: { x: 19, y: 6 }, end: { x: 19, y: 6 } },
    { type: "wall", start: { x: 20, y: 6 }, end: { x: 20, y: 6 } },
    { type: "wall", start: { x: 21, y: 6 }, end: { x: 21, y: 6 } },
    { type: "wall", start: { x: 2, y: 8 }, end: { x: 2, y: 8 } },
    { type: "wall", start: { x: 3, y: 8 }, end: { x: 3, y: 8 } },
    { type: "wall", start: { x: 4, y: 8 }, end: { x: 4, y: 8 } },
    { type: "wall", start: { x: 5, y: 8 }, end: { x: 5, y: 8 } },
    { type: "wall", start: { x: 6, y: 8 }, end: { x: 6, y: 8 } },
    { type: "wall", start: { x: 7, y: 8 }, end: { x: 7, y: 8 } },
    { type: "wall", start: { x: 9, y: 8 }, end: { x: 9, y: 8 } },
    { type: "wall", start: { x: 10, y: 8 }, end: { x: 10, y: 8 } },
    { type: "wall", start: { x: 11, y: 8 }, end: { x: 11, y: 8 } },
    { type: "wall", start: { x: 12, y: 8 }, end: { x: 12, y: 8 } },
    { type: "wall", start: { x: 13, y: 8 }, end: { x: 13, y: 8 } },
    { type: "wall", start: { x: 14, y: 8 }, end: { x: 14, y: 8 } },
    { type: "wall", start: { x: 16, y: 8 }, end: { x: 16, y: 8 } },
    { type: "wall", start: { x: 17, y: 8 }, end: { x: 17, y: 8 } },
    { type: "wall", start: { x: 18, y: 8 }, end: { x: 18, y: 8 } },
    { type: "wall", start: { x: 19, y: 8 }, end: { x: 19, y: 8 } },
    { type: "wall", start: { x: 20, y: 8 }, end: { x: 20, y: 8 } },
    { type: "wall", start: { x: 21, y: 8 }, end: { x: 21, y: 8 } },
    { type: "wall", start: { x: 2, y: 9 }, end: { x: 2, y: 9 } },
    { type: "wall", start: { x: 3, y: 9 }, end: { x: 3, y: 9 } },
    { type: "wall", start: { x: 4, y: 9 }, end: { x: 4, y: 9 } },
    { type: "wall", start: { x: 5, y: 9 }, end: { x: 5, y: 9 } },
    { type: "wall", start: { x: 6, y: 9 }, end: { x: 6, y: 9 } },
    { type: "wall", start: { x: 7, y: 9 }, end: { x: 7, y: 9 } },
    { type: "wall", start: { x: 9, y: 9 }, end: { x: 9, y: 9 } },
    { type: "wall", start: { x: 10, y: 9 }, end: { x: 10, y: 9 } },
    { type: "wall", start: { x: 11, y: 9 }, end: { x: 11, y: 9 } },
    { type: "wall", start: { x: 12, y: 9 }, end: { x: 12, y: 9 } },
    { type: "wall", start: { x: 13, y: 9 }, end: { x: 13, y: 9 } },
    { type: "wall", start: { x: 14, y: 9 }, end: { x: 14, y: 9 } },
    { type: "wall", start: { x: 16, y: 9 }, end: { x: 16, y: 9 } },
    { type: "wall", start: { x: 17, y: 9 }, end: { x: 17, y: 9 } },
    { type: "wall", start: { x: 18, y: 9 }, end: { x: 18, y: 9 } },
    { type: "wall", start: { x: 19, y: 9 }, end: { x: 19, y: 9 } },
    { type: "wall", start: { x: 20, y: 9 }, end: { x: 20, y: 9 } },
    { type: "wall", start: { x: 21, y: 9 }, end: { x: 21, y: 9 } },
    { type: "wall", start: { x: 0, y: 10 }, end: { x: 0, y: 10 } },
    { type: "wall", start: { x: 1, y: 10 }, end: { x: 1, y: 10 } },
    { type: "wall", start: { x: 2, y: 10 }, end: { x: 2, y: 10 } },
    { type: "wall", start: { x: 3, y: 10 }, end: { x: 3, y: 10 } },
    { type: "wall", start: { x: 21, y: 10 }, end: { x: 21, y: 10 } },
    { type: "wall", start: { x: 22, y: 10 }, end: { x: 22, y: 10 } },
    { type: "wall", start: { x: 23, y: 10 }, end: { x: 23, y: 10 } },
    { type: "wall", start: { x: 24, y: 10 }, end: { x: 24, y: 10 } },
    { type: "wall", start: { x: 0, y: 11 }, end: { x: 0, y: 11 } },
    { type: "wall", start: { x: 9, y: 11 }, end: { x: 9, y: 11 } },
    { type: "wall", start: { x: 10, y: 11 }, end: { x: 10, y: 11 } },
    { type: "wall", start: { x: 11, y: 11 }, end: { x: 11, y: 11 } },
    { type: "wall", start: { x: 12, y: 11 }, end: { x: 12, y: 11 } },
    { type: "wall", start: { x: 13, y: 11 }, end: { x: 13, y: 11 } },
    { type: "wall", start: { x: 14, y: 11 }, end: { x: 14, y: 11 } },
    { type: "wall", start: { x: 24, y: 11 }, end: { x: 24, y: 11 } },
    { type: "wall", start: { x: 0, y: 12 }, end: { x: 0, y: 12 } },
    { type: "wall", start: { x: 9, y: 12 }, end: { x: 9, y: 12 } },
    { type: "wall", start: { x: 10, y: 12 }, end: { x: 10, y: 12 } },
    { type: "wall", start: { x: 11, y: 12 }, end: { x: 11, y: 12 } },
    { type: "wall", start: { x: 12, y: 12 }, end: { x: 12, y: 12 } },
    { type: "wall", start: { x: 13, y: 12 }, end: { x: 13, y: 12 } },
    { type: "wall", start: { x: 14, y: 12 }, end: { x: 14, y: 12 } },
    { type: "wall", start: { x: 24, y: 12 }, end: { x: 24, y: 12 } },
    { type: "wall", start: { x: 0, y: 13 }, end: { x: 0, y: 13 } },
    { type: "wall", start: { x: 1, y: 13 }, end: { x: 1, y: 13 } },
    { type: "wall", start: { x: 2, y: 13 }, end: { x: 2, y: 13 } },
    { type: "wall", start: { x: 3, y: 13 }, end: { x: 3, y: 13 } },
    { type: "wall", start: { x: 21, y: 13 }, end: { x: 21, y: 13 } },
    { type: "wall", start: { x: 22, y: 13 }, end: { x: 22, y: 13 } },
    { type: "wall", start: { x: 23, y: 13 }, end: { x: 23, y: 13 } },
    { type: "wall", start: { x: 24, y: 13 }, end: { x: 24, y: 13 } },
    { type: "wall", start: { x: 2, y: 14 }, end: { x: 2, y: 14 } },
    { type: "wall", start: { x: 3, y: 14 }, end: { x: 3, y: 14 } },
    { type: "wall", start: { x: 4, y: 14 }, end: { x: 4, y: 14 } },
    { type: "wall", start: { x: 5, y: 14 }, end: { x: 5, y: 14 } },
    { type: "wall", start: { x: 6, y: 14 }, end: { x: 6, y: 14 } },
    { type: "wall", start: { x: 7, y: 14 }, end: { x: 7, y: 14 } },
    { type: "wall", start: { x: 9, y: 14 }, end: { x: 9, y: 14 } },
    { type: "wall", start: { x: 10, y: 14 }, end: { x: 10, y: 14 } },
    { type: "wall", start: { x: 11, y: 14 }, end: { x: 11, y: 14 } },
    { type: "wall", start: { x: 12, y: 14 }, end: { x: 12, y: 14 } },
    { type: "wall", start: { x: 13, y: 14 }, end: { x: 13, y: 14 } },
    { type: "wall", start: { x: 14, y: 14 }, end: { x: 14, y: 14 } },
    { type: "wall", start: { x: 16, y: 14 }, end: { x: 16, y: 14 } },
    { type: "wall", start: { x: 17, y: 14 }, end: { x: 17, y: 14 } },
    { type: "wall", start: { x: 18, y: 14 }, end: { x: 18, y: 14 } },
    { type: "wall", start: { x: 19, y: 14 }, end: { x: 19, y: 14 } },
    { type: "wall", start: { x: 20, y: 14 }, end: { x: 20, y: 14 } },
    { type: "wall", start: { x: 21, y: 14 }, end: { x: 21, y: 14 } },
    { type: "wall", start: { x: 2, y: 15 }, end: { x: 2, y: 15 } },
    { type: "wall", start: { x: 3, y: 15 }, end: { x: 3, y: 15 } },
    { type: "wall", start: { x: 4, y: 15 }, end: { x: 4, y: 15 } },
    { type: "wall", start: { x: 5, y: 15 }, end: { x: 5, y: 15 } },
    { type: "wall", start: { x: 6, y: 15 }, end: { x: 6, y: 15 } },
    { type: "wall", start: { x: 7, y: 15 }, end: { x: 7, y: 15 } },
    { type: "wall", start: { x: 9, y: 15 }, end: { x: 9, y: 15 } },
    { type: "wall", start: { x: 10, y: 15 }, end: { x: 10, y: 15 } },
    { type: "wall", start: { x: 11, y: 15 }, end: { x: 11, y: 15 } },
    { type: "wall", start: { x: 12, y: 15 }, end: { x: 12, y: 15 } },
    { type: "wall", start: { x: 13, y: 15 }, end: { x: 13, y: 15 } },
    { type: "wall", start: { x: 14, y: 15 }, end: { x: 14, y: 15 } },
    { type: "wall", start: { x: 16, y: 15 }, end: { x: 16, y: 15 } },
    { type: "wall", start: { x: 17, y: 15 }, end: { x: 17, y: 15 } },
    { type: "wall", start: { x: 18, y: 15 }, end: { x: 18, y: 15 } },
    { type: "wall", start: { x: 19, y: 15 }, end: { x: 19, y: 15 } },
    { type: "wall", start: { x: 20, y: 15 }, end: { x: 20, y: 15 } },
    { type: "wall", start: { x: 21, y: 15 }, end: { x: 21, y: 15 } },
    { type: "wall", start: { x: 2, y: 17 }, end: { x: 2, y: 17 } },
    { type: "wall", start: { x: 3, y: 17 }, end: { x: 3, y: 17 } },
    { type: "wall", start: { x: 4, y: 17 }, end: { x: 4, y: 17 } },
    { type: "wall", start: { x: 5, y: 17 }, end: { x: 5, y: 17 } },
    { type: "wall", start: { x: 6, y: 17 }, end: { x: 6, y: 17 } },
    { type: "wall", start: { x: 7, y: 17 }, end: { x: 7, y: 17 } },
    { type: "wall", start: { x: 9, y: 17 }, end: { x: 9, y: 17 } },
    { type: "wall", start: { x: 10, y: 17 }, end: { x: 10, y: 17 } },
    { type: "wall", start: { x: 11, y: 17 }, end: { x: 11, y: 17 } },
    { type: "wall", start: { x: 12, y: 17 }, end: { x: 12, y: 17 } },
    { type: "wall", start: { x: 13, y: 17 }, end: { x: 13, y: 17 } },
    { type: "wall", start: { x: 14, y: 17 }, end: { x: 14, y: 17 } },
    { type: "wall", start: { x: 16, y: 17 }, end: { x: 16, y: 17 } },
    { type: "wall", start: { x: 17, y: 17 }, end: { x: 17, y: 17 } },
    { type: "wall", start: { x: 18, y: 17 }, end: { x: 18, y: 17 } },
    { type: "wall", start: { x: 19, y: 17 }, end: { x: 19, y: 17 } },
    { type: "wall", start: { x: 20, y: 17 }, end: { x: 20, y: 17 } },
    { type: "wall", start: { x: 21, y: 17 }, end: { x: 21, y: 17 } },
    { type: "wall", start: { x: 2, y: 18 }, end: { x: 2, y: 18 } },
    { type: "wall", start: { x: 3, y: 18 }, end: { x: 3, y: 18 } },
    { type: "wall", start: { x: 4, y: 18 }, end: { x: 4, y: 18 } },
    { type: "wall", start: { x: 5, y: 18 }, end: { x: 5, y: 18 } },
    { type: "wall", start: { x: 6, y: 18 }, end: { x: 6, y: 18 } },
    { type: "wall", start: { x: 7, y: 18 }, end: { x: 7, y: 18 } },
    { type: "wall", start: { x: 9, y: 18 }, end: { x: 9, y: 18 } },
    { type: "wall", start: { x: 10, y: 18 }, end: { x: 10, y: 18 } },
    { type: "wall", start: { x: 11, y: 18 }, end: { x: 11, y: 18 } },
    { type: "wall", start: { x: 12, y: 18 }, end: { x: 12, y: 18 } },
    { type: "wall", start: { x: 13, y: 18 }, end: { x: 13, y: 18 } },
    { type: "wall", start: { x: 14, y: 18 }, end: { x: 14, y: 18 } },
    { type: "wall", start: { x: 16, y: 18 }, end: { x: 16, y: 18 } },
    { type: "wall", start: { x: 17, y: 18 }, end: { x: 17, y: 18 } },
    { type: "wall", start: { x: 18, y: 18 }, end: { x: 18, y: 18 } },
    { type: "wall", start: { x: 19, y: 18 }, end: { x: 19, y: 18 } },
    { type: "wall", start: { x: 20, y: 18 }, end: { x: 20, y: 18 } },
    { type: "wall", start: { x: 21, y: 18 }, end: { x: 21, y: 18 } },
    { type: "wall", start: { x: 2, y: 20 }, end: { x: 2, y: 20 } },
    { type: "wall", start: { x: 3, y: 20 }, end: { x: 3, y: 20 } },
    { type: "wall", start: { x: 4, y: 20 }, end: { x: 4, y: 20 } },
    { type: "wall", start: { x: 5, y: 20 }, end: { x: 5, y: 20 } },
    { type: "wall", start: { x: 6, y: 20 }, end: { x: 6, y: 20 } },
    { type: "wall", start: { x: 7, y: 20 }, end: { x: 7, y: 20 } },
    { type: "wall", start: { x: 16, y: 20 }, end: { x: 16, y: 20 } },
    { type: "wall", start: { x: 17, y: 20 }, end: { x: 17, y: 20 } },
    { type: "wall", start: { x: 18, y: 20 }, end: { x: 18, y: 20 } },
    { type: "wall", start: { x: 19, y: 20 }, end: { x: 19, y: 20 } },
    { type: "wall", start: { x: 20, y: 20 }, end: { x: 20, y: 20 } },
    { type: "wall", start: { x: 21, y: 20 }, end: { x: 21, y: 20 } },
    { type: "wall", start: { x: 2, y: 21 }, end: { x: 2, y: 21 } },
    { type: "wall", start: { x: 3, y: 21 }, end: { x: 3, y: 21 } },
    { type: "wall", start: { x: 4, y: 21 }, end: { x: 4, y: 21 } },
    { type: "wall", start: { x: 5, y: 21 }, end: { x: 5, y: 21 } },
    { type: "wall", start: { x: 6, y: 21 }, end: { x: 6, y: 21 } },
    { type: "wall", start: { x: 7, y: 21 }, end: { x: 7, y: 21 } },
    { type: "wall", start: { x: 10, y: 21 }, end: { x: 10, y: 21 } },
    { type: "wall", start: { x: 13, y: 21 }, end: { x: 13, y: 21 } },
    { type: "wall", start: { x: 16, y: 21 }, end: { x: 16, y: 21 } },
    { type: "wall", start: { x: 17, y: 21 }, end: { x: 17, y: 21 } },
    { type: "wall", start: { x: 18, y: 21 }, end: { x: 18, y: 21 } },
    { type: "wall", start: { x: 19, y: 21 }, end: { x: 19, y: 21 } },
    { type: "wall", start: { x: 20, y: 21 }, end: { x: 20, y: 21 } },
    { type: "wall", start: { x: 21, y: 21 }, end: { x: 21, y: 21 } },
    { type: "wall", start: { x: 10, y: 22 }, end: { x: 10, y: 22 } },
    { type: "wall", start: { x: 13, y: 22 }, end: { x: 13, y: 22 } },
    { type: "wall", start: { x: 10, y: 23 }, end: { x: 10, y: 23 } },
    { type: "wall", start: { x: 13, y: 23 }, end: { x: 13, y: 23 } },
    { type: "wall", start: { x: 10, y: 24 }, end: { x: 10, y: 24 } },
    { type: "wall", start: { x: 11, y: 24 }, end: { x: 11, y: 24 } },
    { type: "wall", start: { x: 12, y: 24 }, end: { x: 12, y: 24 } },
    { type: "wall", start: { x: 13, y: 24 }, end: { x: 13, y: 24 } },
  ],
  objects: {
    count: 20,
    spawn_zones: [{ x_range: [4, 20], y_range: [4, 19], probability: 1 }],
  },
  agents: {
    scouts: {
      count: 2,
      spawn_location: { x: 12, y: 12 },
      parameters: {
        vision_radius: 5,
        communication_radius: 15,
        max_energy: 100,
        speed: 1.5,
        carrying_capacity: 0,
      },
    },
    coordinators: {
      count: 1,
      spawn_location: { x: 12, y: 12 },
      parameters: {
        vision_radius: 7,
        communication_radius: 20,
        max_energy: 120,
        speed: 1,
        carrying_capacity: 0,
      },
    },
    retrievers: {
      count: 3,
      spawn_location: { x: 12, y: 12 },
      parameters: {
        vision_radius: 4,
        communication_radius: 12,
        max_energy: 100,
        speed: 1,
        carrying_capacity: 2,
      },
    },
  },
  logging: {
    enabled: true,
    log_interval: 10,
    metrics: ["coverage", "energy", "objects_retrieved"],
  },
};

export const MAP_PRESETS: MapPreset[] = [
  {
    id: "pavone",
    label: "Pavone",
    description: "Layout base a 4 zone con corridoi interni",
    config: pavone,
  },
  {
    id: "pavone_complex",
    label: "Pavone Complex",
    description:
      "Layout complesso con scaffalature dense e più zone intermedie",
    config: pavoneComplex,
  },
];
